from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

# ─── Token ─────────────────────────────────────────────────────────────────────

class Token(BaseModel):
    access_token: str
    token_type: str
    role: str
    must_change_password: bool
    full_name: Optional[str] = None
    user_id: int

class TokenData(BaseModel):
    username: Optional[str] = None

# ─── Site ──────────────────────────────────────────────────────────────────────

class SiteBase(BaseModel):
    name: str
    description: Optional[str] = None

class SiteCreate(SiteBase):
    pass

class Site(SiteBase):
    id: int
    created_at: datetime
    class Config:
        from_attributes = True

# ─── User ──────────────────────────────────────────────────────────────────────

class UserBase(BaseModel):
    username: str
    full_name: Optional[str] = None
    role: str = "monitor"

class UserCreate(UserBase):
    pass  # password is auto-generated by server

class UserUpdate(BaseModel):
    full_name: Optional[str] = None
    role: Optional[str] = None
    is_active: Optional[bool] = None

class User(UserBase):
    id: int
    is_active: bool
    must_change_password: bool
    created_at: datetime
    assigned_sites: List[Site] = []
    class Config:
        from_attributes = True

class AssignSitesRequest(BaseModel):
    site_ids: List[int]

class ChangePasswordRequest(BaseModel):
    old_password: str
    new_password: str

# ─── Switch ────────────────────────────────────────────────────────────────────

class SwitchBase(BaseModel):
    ip_address: str
    hostname: str
    username: str
    site_id: Optional[int] = None
    location_area: Optional[str] = None
    model: Optional[str] = "Cisco Catalyst 2960"
    tags: Optional[list[str]] = []

class SwitchCreate(SwitchBase):
    password: str

class SwitchUpdate(BaseModel):
    ip_address: Optional[str] = None
    hostname: Optional[str] = None
    username: Optional[str] = None
    password: Optional[str] = None
    site_id: Optional[int] = None
    location_area: Optional[str] = None
    model: Optional[str] = None
    tags: Optional[list[str]] = None

class Switch(SwitchBase):
    id: int
    status: str
    last_checked: datetime
    site: Optional[Site] = None
    class Config:
        from_attributes = True

# ─── Audit Log ─────────────────────────────────────────────────────────────────

class AuditLogBase(BaseModel):
    switch_id: int
    switch_ip: str
    action: str
    interface: Optional[str] = None
    old_value: Optional[str] = None
    new_value: Optional[str] = None
    user: Optional[str] = "admin"
    status: Optional[str] = "success"

class AuditLog(AuditLogBase):
    id: int
    timestamp: datetime
    class Config:
        from_attributes = True

# ─── Port Action Requests ──────────────────────────────────────────────────────

class SetDescriptionRequest(BaseModel):
    interface: str
    description: str

class SetVlanRequest(BaseModel):
    interface: str
    vlan_id: str

class PortActionRequest(BaseModel):
    interface: str
    user: Optional[str] = "admin"

class BulkPortActionRequest(BaseModel):
    interfaces: List[str]
